post-fix calculation complete
MrButak/Programming-practice-problems pull request #3
Opened 2022-04-28 22:09 UTC by MrButak

Requesting code review. Thank you John.

2022-04-29 23:15 UTC, JohnnyCurran requested changes
Glad your solution is working :) Left a couple comments to address

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +    let solutions = [11, 14, 22, 45, -521, 0];
Equation/solution is essentially a key-value pair (i.e. this equation maps to this solution). When you have key/value pairs, prefer to use objects over arrays where the indices line up. (e.g. index 0 of this array should map to index 0 of this different array). Arrays with matching indices tend to be error-prone and obscure the relationship between your data.

Prefer an approach like:
```js
equations = {
  '1 3 4 * + 2 -': 11,
  '2 3 4 * +': 14
  // other equations here
}
```

The key of the object does not have to be the equation itself. You could even take an approach with an array of objects that have 'equation' and 'solution' keys (In JS, I think this might even be better than the above):

```js
equations = [
 {
    equation: '1 3 4 * + 2 -',
    solution: 11
  },
 // Other objects here
]

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +        console.assert(calculatePostFix(equations[i].split(' ')) === solutions[i]);
Excellent use of `console.assert` here

You'll need to update this line if you make the array -> object change above

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +    if(equation.length < 2) {return equation[0]};
Put this early return at the top of the function. If you have conditions that need to be met in order for the function to run (like needing at least 2 elements in the array), check those at the beginning of your function and exit if they are not met.

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +        if(Number.isNaN(parseInt(item))) {
Put the `Number.isNaN(parseInt(item))` into its own function named `isOperator` for better readability

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +        numberCount++;
Put this in an explicit else block and add a comment like `// Not an operator`

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +                partialSolution = doMath(equation[3], parseInt(equation[1]), parseInt(equation[2]));
Assign the `equation[]` index accesses their own variable names for better readability e.g. `operator`

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +                equation.splice([1], 3);
How come the 1 is wrapped in an array here?

2022-04-29 23:15 UTC, JohnnyCurran commented on Post-fix-notation-calculator/post-fix-calculator.js
> +                partialSolution = doMath(equation[2], parseInt(equation[0]), parseInt(equation[1]));
Assign these `equation[]` array accesses to variables with names describing what they are

2022-05-02 13:34 UTC, MrButak commented on Post-fix-notation-calculator/post-fix-calculator.js
> +                equation.splice([1], 3);
I didn't fully understand splice. I thought because I was splicing an array I had to put it in a bracket. It's fixed.

2022-05-02 13:38 UTC, merged